### ISSUE TITLE
Static builds can't find static library

### ISSUE THREAD

**Issue by creichen** [Lokathor/sdl3-sys-rs#4]
Compiling with `static-link` fails for me, with
```
   Compiling sdl3-sys v0.0.4+sdl3-dev-2023-04-16 (/home/user/SDL/sdl3-sys-rs)
     Running `rustc --crate-name sdl3_sys --edition=2021 /home/user/SDL/sdl3-sys-rs/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="static-link"' -C metadata=9d3a66688eab8e72 -C extra-filename=-9d3a66688eab8e72 --out-dir /home/user/SDL/my-rust-project/target/debug/deps -C incremental=/home/user/SDL/my-rust-project/target/debug/incremental -L dependency=/home/user/SDL/my-rust-project/target/debug/deps --extern libc=/home/user/SDL/my-rust-project/target/debug/deps/liblibc-44d36927f8410ebd.rmeta -l static=SDL3`
     Running `/home/user/SDL/my-rust-project/target/debug/build/sdl3-913037937dcc8026/build-script-build`
     Running `rustc --crate-name sdl3 /home/user/SDL/sdl3-rs/src/sdl3/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="static-link"' -C metadata=9f50803b8069c524 -C extra-filename=-9f50803b8069c524 --out-dir /home/user/SDL/my-rust-project/target/debug/deps -C incremental=/home/user/SDL/my-rust-project/target/debug/incremental -L dependency=/home/user/SDL/my-rust-project/target/debug/deps --extern bitflags=/home/user/SDL/my-rust-project/target/debug/deps/libbitflags-e7fcb7138abfa89d.rmeta --extern lazy_static=/home/user/SDL/my-rust-project/target/debug/deps/liblazy_static-1e3d64e37277e545.rmeta --extern libc=/home/user/SDL/my-rust-project/target/debug/deps/liblibc-44d36927f8410ebd.rmeta --extern sdl3_sys=/home/user/SDL/my-rust-project/target/debug/deps/libsdl3_sys-9d3a66688eab8e72.rmeta`
error: could not find native static library `SDL3`, perhaps an -L flag is missing?
```

I have temporarily worked around this by copying my personal `libSDL3.a` to `/usr/local/lib` and using `cargo:rustc-link-search=/usr/local/lib`, but it seems to me that there should be a way to link against the `libSDL3.a` that `sdl3-sys` itself builds.

(Background: I am working on creating SDL3 bindings for new features in an open SDL3 pull request and thus need fairly tight control over the exact SDL3 revision; I am avoiding dynamic linking to reduce the number of points of failure during debugging.)

**Comment by Lokathor** [comment]
Adding the `bundled` feature to your build may work? That should cause the bundled build to emit the correct link line so that it can be found in whatever temporary path it was built to.

**Comment by creichen** [comment]
That did the trick, thank you!
This might be too obscure to write a `README.md` for, but let me know if you think that it'd be worth it-- I'd be happy to send a PR for one.

**Comment by Lokathor** [comment]
The entire current build system isn't intended to live too long, probably. However, since SDL3 isn't officially released this crate hasn't had much effort invested into it. Once SDL3 has a stable release basically everything top to bottom will get a look.
